// Changent Design System — build
// tokens/*.tokens.json (DTCG)  →  dist/tokens.css · dist/tailwind.css · dist/tokens.ts · dist/tokens.resolved.json
//                                →  powerbi/changent-powerbi-theme.json
import StyleDictionary from 'style-dictionary';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const out = (p, s) => { fs.mkdirSync(path.dirname(path.join(root, p)), { recursive: true }); fs.writeFileSync(path.join(root, p), s); };
const header = `Changent Design System v${pkg.version} — GENERATED by scripts/build.mjs. Do not edit; change tokens/*.tokens.json instead.`;

async function tokensFor(sources) {
  const sd = new StyleDictionary({
    source: sources.map((s) => path.join(root, 'tokens', s)),
    log: { verbosity: 'silent', warnings: 'disabled' },
    platforms: { css: { transformGroup: 'css', prefix: 'cds' } },
  });
  return (await sd.getPlatformTokens('css')).allTokens;
}

const light = await tokensFor(['primitives.tokens.json', 'semantic.tokens.json', 'dataviz.tokens.json']);
const darkAll = await tokensFor(['primitives.tokens.json', 'semantic.tokens.json', 'semantic.dark.tokens.json']);
const dark = darkAll.filter((t) => t.filePath.endsWith('semantic.dark.tokens.json') && t.path[1] !== 'night');

// value lookup by dotted path: v('color.text.primary')
const byPath = Object.fromEntries(light.map((t) => [t.path.join('.'), t]));
const darkByPath = Object.fromEntries(darkAll.map((t) => [t.path.join('.'), t]));
const v = (p, src = byPath) => { const t = src[p]; if (!t) throw new Error(`Unknown token ${p}`); return t.$value ?? t.value; };
const hex = (p, src) => String(v(p, src)).toUpperCase();

// ---------- 1. CSS variables (light + dark) ----------
const cssVar = (t) => `  --${t.name}: ${t.$value ?? t.value};`;
out('dist/tokens.css', `/* ${header} */

:root {
${light.map(cssVar).join('\n')}
}

.dark, [data-theme="dark"] {
${dark.map(cssVar).join('\n')}
}
`);

// ---------- 2. Tailwind v4 + shadcn/ui mapping ----------
const shadcn = {
  background: 'surface-default', foreground: 'text-primary',
  card: 'surface-raised', 'card-foreground': 'text-primary',
  popover: 'surface-raised', 'popover-foreground': 'text-primary',
  primary: 'interactive-primary', 'primary-foreground': 'interactive-on-primary',
  secondary: 'interactive-secondary', 'secondary-foreground': 'interactive-on-secondary',
  muted: 'surface-nav', 'muted-foreground': 'text-secondary',
  accent: 'surface-accent', 'accent-foreground': 'text-brand',
  destructive: 'status-danger-fill', 'destructive-foreground': 'status-danger-on-fill',
  success: 'status-success-fill', 'success-foreground': 'status-success-on-fill',
  warning: 'status-warning-fill', 'warning-foreground': 'status-warning-on-fill',
  info: 'status-info-fill', 'info-foreground': 'status-info-on-fill',
  border: 'border-default', input: 'border-default', ring: 'border-focus', divider: 'border-divider',
  sidebar: 'surface-nav', 'sidebar-foreground': 'text-secondary',
  'sidebar-primary': 'interactive-primary', 'sidebar-primary-foreground': 'interactive-on-primary',
  'sidebar-accent': 'surface-accent-strong', 'sidebar-accent-foreground': 'text-brand',
  'sidebar-border': 'border-divider', 'sidebar-ring': 'border-focus',
  ...Object.fromEntries([1, 2, 3, 4, 5, 6].map((i) => [`chart-${i}`, `chart-categorical-${i}`])),
};
out('dist/tailwind.css', `/* ${header}
   Usage (Tailwind v4 + shadcn/ui):
     @import "tailwindcss";
     @import "@changent/design-system/tailwind.css";
*/
@import "./tokens.css";

:root {
${Object.entries(shadcn).map(([k, t]) => `  --${k}: var(--cds-color-${t});`).join('\n')}
  --radius: var(--cds-radius-md);
}

@theme inline {
  --font-sans: var(--cds-font-family-base);
${Object.keys(shadcn).map((k) => `  --color-${k}: var(--${k});`).join('\n')}
  --radius-sm: var(--cds-radius-sm);
  --radius-md: var(--cds-radius-md);
  --radius-lg: var(--cds-radius-lg);
  --shadow-card: var(--cds-shadow-card);
  /* Type scale — 14px is the content minimum; 12px (text-caption) only for tooltips, footnotes, legends, axis titles */
  --text-caption: 12px;
  --text-body: 14px;
  --text-title: 16px;
  --text-h2: 18px;
  --text-h1: 24px;
  --text-kpi: 32px;
}
`);

// ---------- 3. TypeScript (for Recharts / JS charts) ----------
const seq = (name) => [1, 2, 3, 4, 5].map((i) => hex(`color.chart.sequential.${name}.${i}`));
const five = (p) => [1, 2, 3, 4, 5].map((i) => hex(`${p}.${i}`));
const ts = {
  categorical: [1, 2, 3, 4, 5, 6].map((i) => hex(`color.chart.categorical.${i}`)),
  sequential: { blue: seq('blue'), cyan: seq('cyan'), green: seq('green'), orange: seq('orange') },
  diverging: { kpi: five('color.chart.diverging.kpi'), financial: five('color.chart.diverging.financial') },
  priority: five('color.chart.priority'),
  gridline: hex('color.chart.gridline'), axisLabel: hex('color.chart.axis-label'), nodata: hex('color.chart.nodata'),
  status: Object.fromEntries(['success', 'warning', 'danger', 'info', 'neutral'].map((s) => [s,
    Object.fromEntries(['fill', 'text', 'on-fill', 'tint'].map((k) => [k.replace('-f', 'F'), hex(`color.status.${s}.${k}`)]))])),
  text: { primary: hex('color.text.primary'), secondary: hex('color.text.secondary'), muted: hex('color.text.muted'), brand: hex('color.text.brand') },
  border: { default: hex('color.border.default'), divider: hex('color.border.divider') },
  font: { family: v('font.family.base'), size: { caption: 12, body: 14, title: 16, h2: 18, h1: 24, kpi: 32 } },
};
out('dist/tokens.js', `// ${header}
export const chart = ${JSON.stringify(ts, null, 2)};
export default chart;
`);
out('dist/tokens.d.ts', `// ${header}
export declare const chart: ${JSON.stringify(ts, null, 2)};
export type ChangentStatus = keyof typeof chart.status;
export default chart;
`);

// ---------- 4. Resolved dump (used by tests / Figma prep) ----------
out('dist/tokens.resolved.json', JSON.stringify({
  light: Object.fromEntries(light.map((t) => [t.path.join('.'), t.$value ?? t.value])),
  dark: Object.fromEntries(dark.map((t) => [t.path.join('.'), t.$value ?? t.value])),
}, null, 2));

// ---------- 5. Power BI report theme ----------
// Power BI uses points. Rule: 14 for content (titles, data labels, table cells, slicer items), 12 only for axis, legends, tooltips.
const FONT = 'Segoe UI';
const C = {
  ink: hex('color.text.primary'), ink2: hex('color.text.secondary'), muted: hex('color.text.muted'), brand: hex('color.text.brand'),
  white: hex('color.surface.default'), nav: hex('color.surface.nav'), subtle: hex('color.surface.subtle'), accent: hex('color.surface.accent'),
  border: hex('color.border.default'), divider: hex('color.border.divider'),
};
const fill = (c) => ({ solid: { color: c } });
const txt = (size, color, extra = {}) => ({ fontFamily: FONT, fontSize: size, ...(color && { fontColor: fill(color) }), ...extra });
const axis = { fontFamily: FONT, fontSize: 12, labelColor: fill(C.muted), titleFontFamily: FONT, titleFontSize: 12, titleColor: fill(C.muted), gridlineColor: fill(C.divider) };
const legend = { fontFamily: FONT, fontSize: 12, labelColor: fill(C.ink) };
const cartesian = (defaultColor = hex('color.chart.categorical.1')) => ({
  categoryAxis: [{ ...axis, gridlineShow: false }],
  valueAxis: [{ ...axis, gridlineShow: true }],
  legend: [legend],
  labels: [{ fontFamily: FONT, fontSize: 14, color: fill(C.ink) }],
  dataPoint: [{ defaultColor: fill(defaultColor) }],
});
const bars = { ...cartesian(), labels: [{ fontFamily: FONT, fontSize: 14, color: fill(C.ink), labelPosition: 'OutsideEnd' }] };
const radial = { legend: [legend], labels: [{ fontFamily: FONT, fontSize: 14, color: fill(C.ink), position: 'outside' }] };
const tableCards = {
  columnHeaders: [{ ...txt(14, C.white), bold: true, backColor: fill(C.brand), alignment: 'Left' }],
  values: [{ fontFamily: FONT, fontSize: 14, fontColorPrimary: fill(C.ink), backColorPrimary: fill(C.white), fontColorSecondary: fill(C.ink), backColorSecondary: fill(C.subtle) }],
  grid: [{ gridVertical: false, gridHorizontal: true, gridHorizontalColor: fill(C.divider), gridHorizontalWeight: 1, outlineColor: fill(hex('color.border.brand')), outlineWeight: 1 }],
};
const total = { ...txt(14, C.white), bold: true, backColor: fill(C.brand) };

const theme = {
  name: `Changent DataViz Theme v${pkg.version}`,
  dataColors: [
    ...ts.categorical,
    hex('color.navy.600'), hex('color.cyan.700'), hex('color.orange.700'), hex('color.green.700'),
  ],
  good: hex('color.status.success.fill'), neutral: hex('color.status.neutral.fill'), bad: hex('color.status.danger.fill'),
  minimum: ts.diverging.kpi[0], center: ts.diverging.kpi[2], maximum: ts.diverging.kpi[4], null: ts.nodata,
  background: C.white, secondaryBackground: C.nav, foreground: C.ink,
  firstLevelElements: C.ink, secondLevelElements: C.ink2, thirdLevelElements: C.divider, fourthLevelElements: C.muted,
  tableAccent: C.brand, hyperlink: C.brand, visitedHyperlink: hex('color.navy.600'), disabledText: hex('color.text.disabled'),
  textClasses: {
    callout: { fontFace: FONT, fontSize: 32, color: C.brand },
    title:   { fontFace: FONT, fontSize: 16, color: C.ink },
    header:  { fontFace: FONT, fontSize: 14, color: C.ink },
    label:   { fontFace: FONT, fontSize: 12, color: C.muted },
  },
  visualStyles: {
    '*': { '*': {
      title: [{ ...txt(14, C.ink), bold: true, show: true }],
      subTitle: [{ ...txt(12, C.muted), show: false }],
      background: [{ show: true, color: fill(C.white), transparency: 0 }],
      border: [{ show: false, color: fill(C.border), radius: 8 }],
      dropShadow: [{ show: false }],
      visualTooltip: [{ fontFamily: FONT, fontSize: 12, titleFontColor: fill(C.muted), valueFontColor: fill(C.ink), background: fill(C.white) }],
    } },
    page: { '*': {
      background: [{ color: fill(C.white), transparency: 0 }],
      outspace: [{ color: fill(C.nav), transparency: 0 }],
      outspacePane: [{ backgroundColor: fill(C.nav), foregroundColor: fill(C.ink), transparency: 0, titleSize: 14, headerSize: 14, fontFamily: FONT, border: true, borderColor: fill(C.border) }],
      filterCard: [{ backgroundColor: fill(C.white), foregroundColor: fill(C.ink), fontFamily: FONT, textSize: 12, border: true, borderColor: fill(C.border), transparency: 0 }],
    } },
    barChart: { '*': bars }, columnChart: { '*': bars },
    clusteredBarChart: { '*': bars }, clusteredColumnChart: { '*': bars },
    lineChart: { '*': cartesian() }, areaChart: { '*': cartesian() },
    scatterChart: { '*': (({ labels, ...rest }) => rest)(cartesian()) },
    pieChart: { '*': radial }, donutChart: { '*': radial },
    waterfallChart: { '*': { categoryAxis: [{ fontFamily: FONT, fontSize: 12, labelColor: fill(C.muted) }], valueAxis: [{ ...axis, gridlineShow: true }], legend: [legend], labels: [{ fontFamily: FONT, fontSize: 14, color: fill(C.ink) }], sentimentColors: [{
      increaseFill: fill(hex('color.status.success.fill')), decreaseFill: fill(hex('color.status.danger.fill')), totalFill: fill(C.brand), otherFill: fill(hex('color.grey.400')) }] } },
    tableEx: { '*': { ...tableCards, total: [total] } },
    pivotTable: { '*': { ...tableCards,
      rowHeaders: [{ ...txt(14, C.ink) }],
      columnTotal: [total], rowTotal: [total],
      subTotals: [{ ...txt(14, C.ink), bold: true, backColor: fill(C.accent) }] } },
    card: { '*': { labels: [{ fontFamily: FONT, fontSize: 32, bold: true, color: fill(C.brand) }], categoryLabels: [{ fontFamily: FONT, fontSize: 14, color: fill(C.muted), show: true }] } },
    cardVisual: { '*': { value: [{ ...txt(32, C.brand), bold: true }], label: [{ ...txt(14, C.muted), show: true }] } },
    multiRowCard: { '*': {
      dataLabels: [{ fontFamily: FONT, fontSize: 16, bold: true, color: fill(C.brand) }],
      categoryLabels: [{ fontFamily: FONT, fontSize: 14, color: fill(C.muted) }],
      cardTitle: [{ fontFamily: FONT, fontSize: 14, color: fill(C.ink) }] } },
    kpi: { '*': { indicator: [{ ...txt(32, C.brand), bold: true, showIcon: true }], goals: [{ fontSize: 14, showGoal: true, showDistance: true }], trendline: [{ show: true }] } },
    gauge: { '*': { calloutValue: [{ fontFamily: FONT, bold: true, color: fill(C.brand) }] } },
    slicer: { '*': {
      header: [{ fontFamily: FONT, textSize: 14, bold: true, fontColor: fill(C.brand), show: true }],
      items: [{ fontFamily: FONT, textSize: 14, fontColor: fill(C.ink) }] } },
  },
};
out('powerbi/changent-powerbi-theme.json', JSON.stringify(theme, null, 2) + '\n');

console.log(`✓ Built v${pkg.version}: ${light.length} light tokens, ${dark.length} dark overrides → dist/ + powerbi/`);
